# Generated by Django 6.0.1 on 2026-02-15 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("library", "0004_alter_referencesentence_difficulty_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="phonemeprogress",
            index=models.Index(
                fields=["user", "current_score"], name="analytics_p_user_id_d6b317_idx"
            ),
        ),
    ]
