# Generated by Django 6.0.1 on 2026-02-07 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("library", "0002_learningpath_phonemeunit_unitphoneme_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("streak", "Streak"),
                            ("practice", "Practice"),
                            ("mastery", "Mastery"),
                            ("social", "Social"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="trophy",
                        help_text="Icon name for SVG rendering",
                        max_length=50,
                    ),
                ),
                ("xp_reward", models.IntegerField(default=50)),
                (
                    "requirement_type",
                    models.CharField(
                        help_text="streak_days, total_attempts, phoneme_mastery, etc.",
                        max_length=50,
                    ),
                ),
                ("requirement_value", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "ordering": ["category", "requirement_value"],
            },
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                            ("diamond", "Diamond"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "min_rank",
                    models.IntegerField(help_text="Minimum rank to stay in league"),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "icon",
                    models.CharField(
                        default="trophy",
                        help_text="Icon name for SVG rendering",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "League",
                "verbose_name_plural": "Leagues",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="streakrecord",
            name="practice_calendar",
            field=models.JSONField(
                default=dict,
                help_text='Calendar data: {"2024-01-15": true, "2024-01-16": true}',
            ),
        ),
        migrations.AddField(
            model_name="streakrecord",
            name="streak_freeze_used_at",
            field=models.DateField(
                blank=True, help_text="Last date streak freeze was used", null=True
            ),
        ),
        migrations.AddField(
            model_name="streakrecord",
            name="streak_freezes_available",
            field=models.IntegerField(
                default=0, help_text="Number of streak freezes user can use"
            ),
        ),
        migrations.CreateModel(
            name="GemTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("earn", "Earned"), ("spend", "Spent")], max_length=10
                    ),
                ),
                ("reason", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gem_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gem Transaction",
                "verbose_name_plural": "Gem Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserGems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_gems", models.IntegerField(default=0)),
                ("gems_spent", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gems",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Gems",
                "verbose_name_plural": "User Gems",
            },
        ),
        migrations.CreateModel(
            name="UserHearts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_hearts", models.IntegerField(default=5)),
                ("last_heart_lost", models.DateTimeField(blank=True, null=True)),
                ("last_heart_refill", models.DateTimeField(blank=True, null=True)),
                (
                    "has_unlimited_hearts",
                    models.BooleanField(
                        default=False,
                        help_text="Premium feature or earned through perfect streaks",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hearts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Hearts",
                "verbose_name_plural": "User Hearts",
            },
        ),
        migrations.CreateModel(
            name="UserLeague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekly_rank", models.IntegerField(default=0)),
                ("promotion_count", models.IntegerField(default=0)),
                ("demotion_count", models.IntegerField(default=0)),
                ("joined_current_league", models.DateField(auto_now_add=True)),
                (
                    "current_league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_members",
                        to="analytics.league",
                    ),
                ),
                (
                    "highest_league",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="peak_members",
                        to="analytics.league",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User League",
                "verbose_name_plural": "User Leagues",
            },
        ),
        migrations.CreateModel(
            name="UserXP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_xp", models.IntegerField(default=0)),
                ("weekly_xp", models.IntegerField(default=0)),
                ("daily_xp", models.IntegerField(default=0)),
                (
                    "daily_xp_goal",
                    models.IntegerField(
                        choices=[
                            (10, "Casual - 10 XP/day"),
                            (20, "Regular - 20 XP/day"),
                            (30, "Serious - 30 XP/day"),
                            (50, "Intense - 50 XP/day"),
                        ],
                        default=20,
                    ),
                ),
                ("current_level", models.IntegerField(default=1)),
                ("last_daily_reset", models.DateField(auto_now_add=True)),
                ("last_weekly_reset", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User XP",
                "verbose_name_plural": "User XP Records",
            },
        ),
        migrations.CreateModel(
            name="XPTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("reason", models.CharField(max_length=100)),
                ("level_after", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "XP Transaction",
                "verbose_name_plural": "XP Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyQuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quest_type",
                    models.CharField(
                        choices=[
                            ("practice_count", "Complete N sentences"),
                            ("streak_maintain", "Maintain streak"),
                            ("perfect_score", "Get N perfect scores"),
                            ("phoneme_focus", "Practice specific phoneme N times"),
                            ("time_challenge", "Practice for N minutes"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "target_value",
                    models.IntegerField(help_text="Target number to complete"),
                ),
                ("current_progress", models.IntegerField(default=0)),
                ("xp_reward", models.IntegerField(default=15)),
                ("gems_reward", models.IntegerField(default=5)),
                ("date", models.DateField()),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_phoneme",
                    models.ForeignKey(
                        blank=True,
                        help_text="For phoneme_focus quests",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.phoneme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_quests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Quest",
                "verbose_name_plural": "Daily Quests",
                "ordering": ["date", "-is_completed"],
                "unique_together": {("user", "date", "quest_type")},
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Friendship",
                "verbose_name_plural": "Friendships",
                "unique_together": {("from_user", "to_user")},
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                ("xp_awarded", models.IntegerField()),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_unlocks",
                        to="analytics.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocked_achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Achievement",
                "verbose_name_plural": "User Achievements",
                "ordering": ["-unlocked_at"],
                "unique_together": {("user", "achievement")},
            },
        ),
        migrations.CreateModel(
            name="WeeklyLeaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                ("weekly_xp", models.IntegerField(default=0)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("promoted", models.BooleanField(default=False)),
                ("demoted", models.BooleanField(default=False)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="analytics.league",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Leaderboard Entry",
                "verbose_name_plural": "Weekly Leaderboard Entries",
                "ordering": ["league", "-weekly_xp"],
                "unique_together": {("user", "week_start")},
            },
        ),
    ]
