# Generated by Django 6.0.1 on 2026-02-10 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoringConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier_thresholds",
                    models.JSONField(
                        default=dict,
                        help_text='Score tier boundaries: {"excellent": 0.9, "good": 0.7, "fair": 0.5}',
                    ),
                ),
                (
                    "per_cutoffs",
                    models.JSONField(
                        default=dict,
                        help_text='PER cutoff values: {"excellent": 0.1, "good": 0.25, "poor": 0.5}',
                    ),
                ),
                (
                    "weak_phoneme_threshold",
                    models.FloatField(
                        default=0.7,
                        help_text="Below this score, a phoneme is considered weak (0-1)",
                    ),
                ),
                (
                    "accuracy_weight",
                    models.FloatField(
                        default=0.7,
                        help_text="Weight for accuracy in final score (0-1)",
                    ),
                ),
                (
                    "fluency_weight",
                    models.FloatField(
                        default=0.3, help_text="Weight for fluency in final score (0-1)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scoring_config_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scoring Config",
                "verbose_name_plural": "Scoring Configs",
            },
        ),
        migrations.CreateModel(
            name="ScoringConfigHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_snapshot",
                    models.JSONField(
                        help_text="Complete config state at time of change"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True, help_text="Reason for config change", max_length=255
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scoring_config_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scoring Config History",
                "verbose_name_plural": "Scoring Config History Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("stt_error", "STT Error"),
                            ("alignment_error", "Alignment Error"),
                            ("system_error", "System Error"),
                            ("tts_error", "TTS Error"),
                            ("llm_error", "LLM Error"),
                            ("security", "Security Event"),
                            ("admin_action", "Admin Action"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="error",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Log",
                "verbose_name_plural": "System Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["type", "created_at"],
                        name="analytics_s_type_417e45_idx",
                    ),
                    models.Index(
                        fields=["severity", "created_at"],
                        name="analytics_s_severit_b25c6e_idx",
                    ),
                ],
            },
        ),
    ]
