# Generated by Django 6.0.1 on 2026-02-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_passwordresettoken_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_id",
            field=models.CharField(
                default="avatar-1",
                help_text="ID of predefined avatar (avatar-1 to avatar-11)",
                max_length=20,
            ),
        ),
    ]
