# Generated by Django 6.0.1 on 2026-02-15 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_avatar_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="daily_goal_target",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Number of sentences the user aims to practice each day",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
    ]
