# Generated by Django 6.0.1 on 2026-04-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_daily_goal_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, help_text='Last time the user made an authenticated request', null=True),
        ),
    ]
