# Generated by Django 6.0.1 on 2026-02-13 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SublevelProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        help_text="Difficulty level: beginner, intermediate, advanced",
                        max_length=20,
                    ),
                ),
                (
                    "sublevel",
                    models.CharField(
                        help_text="Sublevel identifier: 1 or 2", max_length=10
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=1,
                        help_text="Number of times this sublevel was attempted",
                    ),
                ),
                (
                    "average_score",
                    models.FloatField(help_text="Average score across all 5 sentences"),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=True, help_text="Whether all 5 sentences were completed"
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sublevel_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sublevel Progress",
                "verbose_name_plural": "Sublevel Progress",
                "ordering": ["-completed_at"],
                "unique_together": {("user", "level", "sublevel", "completed_at")},
            },
        ),
    ]
