# Generated by Django 6.0.1 on 2026-02-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0003_rename_difficulty_levels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sublevelprogress",
            name="level",
            field=models.CharField(
                choices=[
                    ("core", "Pronunex Core"),
                    ("edge", "Pronunex Edge"),
                    ("elite", "Pronunex Elite"),
                ],
                help_text="Difficulty level: core, edge, elite",
                max_length=20,
            ),
        ),
    ]
