# Generated by Django 6.0.1 on 2026-02-13 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0004_alter_sublevelprogress_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SublevelSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        help_text="Difficulty level: core, edge, elite", max_length=20
                    ),
                ),
                (
                    "sublevel",
                    models.CharField(
                        help_text="Sublevel identifier: 1 or 2", max_length=10
                    ),
                ),
                (
                    "sentence_ids",
                    models.JSONField(
                        help_text="Ordered list of sentence PKs assigned to this sublevel"
                    ),
                ),
                (
                    "current_index",
                    models.IntegerField(
                        default=0,
                        help_text="Index of the sentence the user is currently on (0-based)",
                    ),
                ),
                (
                    "assessment_results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cached assessment results keyed by sentence ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sublevel_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sublevel Session",
                "verbose_name_plural": "Sublevel Sessions",
                "unique_together": {("user", "level", "sublevel")},
            },
        ),
    ]
