# Generated by Django 6.0.1 on 2026-02-14 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0005_create_sublevel_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sublevelsession",
            name="attempted_sentence_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of sentence IDs that have been attempted (for robust progress tracking)",
            ),
        ),
        migrations.AddField(
            model_name="sublevelsession",
            name="is_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has completed all sentences in this sublevel",
            ),
        ),
        migrations.AddField(
            model_name="sublevelsession",
            name="last_active_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Last activity timestamp for soft locking and conflict prevention",
            ),
        ),
        migrations.AddIndex(
            model_name="sublevelsession",
            index=models.Index(
                fields=["user", "level", "sublevel"],
                name="practice_su_user_id_50a99e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sublevelsession",
            index=models.Index(
                fields=["user", "is_completed"], name="practice_su_user_id_3a315a_idx"
            ),
        ),
    ]
