# Generated by Django 6.0.1 on 2026-02-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0004_alter_referencesentence_difficulty_level"),
        ("practice", "0006_sublevelsession_attempted_sentence_ids_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(
                fields=["session", "created_at"], name="practice_at_session_6aa164_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(
                fields=["session", "score"], name="practice_at_session_bcad94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phonemeerror",
            index=models.Index(
                fields=["attempt", "target_phoneme"],
                name="practice_ph_attempt_7f6f58_idx",
            ),
        ),
    ]
